language: csharp
mono:
  - latest
  - 3.12.0
  - 3.10.0
solution: DataSetExtension.sln
script:
  - ./build
  - ./tests
  - grep "Errors: 0, Failures: 0, Inconclusive: 0" build.log
  - grep "Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0" build.log
